version: '3.8'

services:
  fdecono.com:
    image: fdecono.com
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
